# 2026 NCAA Tournament bracket seeds
# Source: Final tournament bracket
# When two teams share a seed, one is picked as placeholder

BRACKET_2026 = {
    "East": {
        1:  "Duke",
        2:  "Michigan St.",
        3:  "Michigan St.",
        4:  "Kansas",
        5:  "St. John's",
        6:  "Louisville",
        7:  "UCLA",
        8:  "Ohio State",
        9:  "TCU",
        10: "UCF",
        11: "South Florida",
        12: "Northern Iowa",
        13: "Cal Baptist",
        14: "N Dakota St.",
        15: "Furman",
        16: "Siena",
    },
    "West": {
        1:  "Arizona",
        2:  "Purdue",
        3:  "Gonzaga",
        4:  "Arkansas",
        5:  "Wisconsin",
        6:  "BYU",
        7:  "Miami FL",
        8:  "Villanova",
        9:  "Utah St.",
        10: "Missouri",
        11: "Texas",
        12: "High Point",
        13: "Kennesaw St.",
        14: "Queens",
        15: "TEX/NCSU",
        16: "Long Island",
    },
    "South": {
        1:  "Florida",
        2:  "Houston",
        3:  "Illinois",
        4:  "Nebraska",
        5:  "Vanderbilt",
        6:  "North Carolina",
        7:  "Saint Mary's",
        8:  "Clemson",
        9:  "Iowa",
        10: "Texas A&M",
        11: "VCU",
        12: "McNeese",
        13: "Troy",
        14: "Penn",
        15: "Idaho",
        16: "Lehigh",
    },
    "Midwest": {
        1:  "Michigan",
        2:  "Iowa St.",
        3:  "Virginia",
        4:  "Alabama",
        5:  "Texas Tech",
        6:  "Tennessee",
        7:  "Kentucky",
        8:  "Georgia",
        9:  "Saint Louis",
        10: "Santa Clara",
        11: "Miami OH",
        12: "Akron",
        13: "Hofstra",
        14: "Wright St.",
        15: "Tennessee St.",
        16: "UMBC",
    },
}