# Estimated 2026 NCAA Tournament bracket seeds
# Source: Pre-tournament projections
# When two teams share a seed, one is picked as placeholder

BRACKET_2026 = {
    "East": {
        1:  "Duke",
        2:  "Michigan St",
        3:  "Iowa State",
        4:  "Gonzaga",
        5:  "Tennessee",
        6:  "Louisville",
        7:  "Villanova",
        8:  "Saint Louis",
        9:  "Iowa",
        10: "TCU",
        11: "Santa Clara",
        12: "Yale",
        13: "UNC Wilmington",
        14: "N Dakota St",
        15: "Wright St",
        16: "C Arkansas",
    },
    "West": {
        1:  "Arizona",
        2:  "Illinois",
        3:  "Kansas",
        4:  "Alabama",
        5:  "St John's",
        6:  "Kentucky",
        7:  "Saint Mary's",
        8:  "Clemson",
        9:  "Missouri",
        10: "SMU",
        11: "Miami OH",
        12: "Belmont",
        13: "High Point",
        14: "Navy",
        15: "ETSU",
        16: "Tennessee St",
    },
    "South": {
        1:  "UConn",
        2:  "Florida",
        3:  "Purdue",
        4:  "Texas Tech",
        5:  "Arkansas",
        6:  "BYU",
        7:  "Utah State",
        8:  "Miami FL",
        9:  "Georgia",
        10: "UCLA",
        11: "Texas A&M",
        12: "South Florida",
        13: "SF Austin",
        14: "Troy",
        15: "Merrimack",
        16: "Long Island",
    },
    "Midwest": {
        1:  "Michigan",
        2:  "Houston",
        3:  "Nebraska",
        4:  "Virginia",
        5:  "Vanderbilt",
        6:  "North Carolina",
        7:  "Wisconsin",
        8:  "UCF",
        9:  "NC State",
        10: "Texas",
        11: "New Mexico",
        12: "Liberty",
        13: "CA Baptist",
        14: "UC Irvine",
        15: "Portland St",
        16: "Howard",
    },
}